name: fx-stack

services:
  fx-db:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${DB_NAME:-fxdb}
      MYSQL_USER: ${DB_USERNAME:-appuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-apppass}

    ports:
      - "${DB_PORT:-3307}:3306"

    volumes:
      - fx-db-data:/var/lib/mysql
      - ./fx-app-spring/ops/fxdb-seed.sql:/docker-entrypoint-initdb.d/01-seed.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  fx-app-spring:
    build: ./fx-app-spring
    image: fx-app-spring:1.0

    ports:
      - "${API_PORT:-8080}:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fx-db:3306/${DB_NAME:-fxdb}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-appuser}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-apppass}

    depends_on:
      fx-db:
        condition: service_healthy

volumes:
  fx-db-data: